wrapperVersion=3.3.4
distributionType=only-script
# 使用阿里云镜像加速国内下载；如在海外可改回 https://repo.maven.apache.org/maven2/...
distributionUrl=https://maven.aliyun.com/repository/public/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
